import type { FaqItem } from '@/lib/schema';

export const colourPredictionTricksFaqs: FaqItem[] = [
  {
    question: 'How does a Colour Prediction round actually work?',
    answer:
      'Each round runs on a fixed countdown. You pick a colour before the timer ends; once it closes, a result is revealed based on the platform\'s own outcome logic, and payout multipliers depend on the colour and the rules in place at that time.',
  },
  {
    question: 'Are there real "tricks" that improve your odds?',
    answer:
      'No verified trick changes the underlying odds — outcomes are generated by the platform\'s system, not a pattern you can read. What experienced players actually do is manage bankroll: fixed bet sizing, a strict stop-loss, and never chasing a losing streak.',
  },
  {
    question: 'Is this game skill-based or pure chance?',
    answer:
      'Chance-based. Treat it as entertainment carrying real financial risk, not a source of guaranteed income, regardless of what any "signal group" claims.',
  },
  {
    question: 'What is the minimum bet amount?',
    answer:
      'Minimums and maximums are set by the official platform and can change without notice — check the live rules in the app before placing a bet rather than relying on this or any other guide.',
  },
  {
    question: 'Can I actually lose money doing this?',
    answer:
      'Yes. Like any real-money prediction game, a losing pick forfeits the wagered amount. Only ever play with money you can afford to lose, and decide your limit before you start.',
  },
];

export const colourPredictionTricksPoints = [
  {
    title: 'Fixed-timer rounds',
    body: 'Rounds close on a short, predictable timer, so results arrive quickly compared with traditional lottery-style draws.',
  },
  {
    title: 'Bankroll discipline over "formulas"',
    body: 'The only sustainable "trick" is a personal staking plan — a fixed unit size and a hard stop-loss — not a paid signal or prediction bot.',
  },
];
